#!/bin/sh -e
# used for initramfs
export PATH
#debugshell "just booted"

mount /proc
mount /sys
mount -o mode=0755 -t tmpfs none /tmp
mknod /dev/tty c 5 1
#mknod /dev/console c 5 1
rm -rf /dev/null
mknod /dev/null c 1 3
mknod /dev/zero c 1 5
mknod /dev/ptmx c 5 2      
chmod 666 /dev/ptmx
mkdir /dev/pts
mkdir /dev/shm
mknod /dev/urandom c 1 9
mknod /dev/random c 1 8
mknod /dev/vchiq c 251 0
chmod a+w /dev/vchiq
mount -o mode=0620 -t devpts none /dev/pts
init='/bin/busybox init'
for i in $(cat /proc/cmdline); do
	case $i in
		init=/init|init=init)
			# Avoid endless loop
			: ;;
		init=*)
			init=${i#init=} ;;
		noshell)
			sed -i '/^tty[23]/s/^/#/' /etc/inittab ;;
	esac
done
#mount /mnt
syslogd -s 100
udevd --daemon
udevadm control --property=STARTUP=1
udevadm trigger --subsystem-match=block --action=add
udevadm settle --timeout=10
udevadm control --property=STARTUP=
echo "Sleeping for 3 seconds"
sleep 3
echo "Done Sleeping"
#udhcpc eth0&
#ifconfig eth0 192.168.1.252/24
echo -e '\33[9;0]\33[14;0]' >> /dev/tty
dropbear -r /dropbear_rsa_host_key -E
hostapd
busybox login
exec $init
